### ISSUE TITLE
Typo on blog page

### ISSUE THREAD

**Issue by sokolic** [kartoza/qgis.org.za#11] opened 2016-11-22 08:25 UTC
There is a typo in the DISQUS section at the bottom of the blog page. The placeholder text for the website input has **webiste** instead of website. Have a look at [https://qgis.org.za/en/blog/first-ever-qgis-cape-town-meetup/](url)

**Comment by timlinux** [comment] 2016-11-22 11:25
Also we should set up a disqus profile for this site rather than using the kartoza one which is currently there by default....

**Comment by gubuntu** [comment] 2016-11-22 11:27
duplicate of #6

**Closed** 2017-02-13 08:42 UTC
