### ISSUE TITLE
fix post-registration url

### ISSUE THREAD

**Issue by gubuntu** [kartoza/qgis.org.za#102] opened 2017-03-27 20:28 UTC
from Jeff:

> when I went to "My Dashboard" and then created a profile account, after creating a user account I was sent https://qgis.org.za/en/ and I could not find a link back to https://foss4g-africa.org/ (that will be very confusing to users who register)

**Comment by euclidian** [comment] 2017-03-28 03:11
duplicates in #91

**Comment by cchristelis** [comment] 2017-04-28 10:04
# Proposed Solution

Update redirect

**Comment by euclidian** [comment] 2017-05-03 03:55
I can't reproduce this. 

I did this procedure
- Signup as a new user
- Get to dashboard
- Create a speaker profile
- Save speaker profile

I was ended up on https://foss4g-africa.org/en/dashboard/

**Comment by euclidian** [comment] 2017-05-17 07:08
can we close this @gubuntu

**Closed** 2017-05-17 08:21 UTC
Labels: bug, foss4g-africa, in progress
